typography_spectrum: 0.12946225656196475
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.1875
  lightness: 0.26472027297131717
  saturation: 0.7427067684475332
  rhythmicContrast: 0.06738576292991638
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.10365645587444305
analytics:
  google: null
  facebook: null
  twitter: null
name: Tigerwon
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Tigerwon
description: Live Streamer/ Producer/ consultant
purpose: []
